rvm:
  - 2.1.5
env:
  - RAILS_ENV=test
script:
  - bundle exec rake db:migrate
  - bundle exec rspec
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server”
after_failure:
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
